// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PkHOLJW3ZElHsJVEcOOcnB16K20AjIc',
    appId: '1:679415860742:web:8705ae9f4269b223e67d87',
    messagingSenderId: '679415860742',
    projectId: 'halisaha-84959',
    authDomain: 'halisaha-84959.firebaseapp.com',
    storageBucket: 'halisaha-84959.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1PkHOLJW3ZElHsJVEcOOcnB16K20AjIc',
    appId: '1:679415860742:android:8705ae9f4269b223e67d87',
    messagingSenderId: '679415860742',
    projectId: 'halisaha-84959',
    storageBucket: 'halisaha-84959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1PkHOLJW3ZElHsJVEcOOcnB16K20AjIc',
    appId: '1:679415860742:ios:8705ae9f4269b223e67d87',
    messagingSenderId: '679415860742',
    projectId: 'halisaha-84959',
    storageBucket: 'halisaha-84959.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1PkHOLJW3ZElHsJVEcOOcnB16K20AjIc',
    appId: '1:679415860742:ios:8705ae9f4269b223e67d87',
    messagingSenderId: '679415860742',
    projectId: 'halisaha-84959',
    storageBucket: 'halisaha-84959.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1PkHOLJW3ZElHsJVEcOOcnB16K20AjIc',
    appId: '1:679415860742:web:8705ae9f4269b223e67d87',
    messagingSenderId: '679415860742',
    projectId: 'halisaha-84959',
    authDomain: 'halisaha-84959.firebaseapp.com',
    storageBucket: 'halisaha-84959.firebasestorage.app',
  );
}
